<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>10.2. Credit Transfer - Failed - Account Not Found</name>
   <tag></tag>
   <elementGuidId>dc9fe326-57df-43a8-ae23-f3f0a5f0a127</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>false</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n\t\&quot;BusMsg\&quot;: {\n\t\t\&quot;AppHdr\&quot;: {\n\t\t\t\&quot;Fr\&quot;: {\n\t\t\t\t\&quot;FIId\&quot;: {\n\t\t\t\t\t\&quot;FinInstnId\&quot;: {\n\t\t\t\t\t\t\&quot;Othr\&quot;: {\n\t\t\t\t\t\t\t\&quot;Id\&quot;: \&quot;${AppHdrId}\&quot;\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t},\n\t\t\t\&quot;To\&quot;: {\n\t\t\t\t\&quot;FIId\&quot;: {\n\t\t\t\t\t\&quot;FinInstnId\&quot;: {\n\t\t\t\t\t\t\&quot;Othr\&quot;: {\n\t\t\t\t\t\t\t\&quot;Id\&quot;: \&quot;${ToId}\&quot;\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t},\n\t\t\t\&quot;BizMsgIdr\&quot;: \&quot;${BizMsgIdr}\&quot;,\n\t\t\t\&quot;MsgDefIdr\&quot;: \&quot;${MsgDefIdr}\&quot;,\n\t\t\t\&quot;BizSvc\&quot;: \&quot;${BizSvc}\&quot;,\n\t\t\t\&quot;CreDt\&quot;: \&quot;${CreDt}\&quot;\n\t\t},\n\t\t\&quot;Document\&quot;: {\n\t\t\t\&quot;FIToFICstmrCdtTrf\&quot;: {\n\t\t\t\t\&quot;GrpHdr\&quot;: {\n\t\t\t\t\t\&quot;MsgId\&quot;: \&quot;${GrpHdrMsgId}\&quot;,\n\t\t\t\t\t\&quot;CreDtTm\&quot;: \&quot;${GrpHdrCreDtTm}\&quot;,\n\t\t\t\t\t\&quot;NbOfTxs\&quot;: \&quot;${GrpHdrNbOfTxs}\&quot;,\n\t\t\t\t\t\&quot;SttlmInf\&quot;: {\n\t\t\t\t\t\t\&quot;SttlmMtd\&quot;: \&quot;${SttlmInfSttlmMtd}\&quot;\n\t\t\t\t\t}\n\t\t\t\t},\n\t\t\t\t\&quot;CdtTrfTxInf\&quot;: [\n\t\t\t\t\t{\n\t\t\t\t\t\t\&quot;PmtId\&quot;: {\n\t\t\t\t\t\t\t\&quot;EndToEndId\&quot;: \&quot;${PmtIdEndToEndId}\&quot;,\n\t\t\t\t\t\t\t\&quot;TxId\&quot;: \&quot;${PmtIdTxId}\&quot;\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\&quot;PmtTpInf\&quot;: {\n\t\t\t\t\t\t\t\&quot;LclInstrm\&quot;: {\n\t\t\t\t\t\t\t\t\&quot;Prtry\&quot;: \&quot;${LclInstrmPrtry}\&quot;\n\t\t\t\t\t\t\t},\n\t\t\t\t\t\t\t\&quot;CtgyPurp\&quot;: {\n\t\t\t\t\t\t\t\t\&quot;Prtry\&quot;: \&quot;${CtgyPurpPrtry}\&quot;\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\&quot;IntrBkSttlmAmt\&quot;: {\n\t\t\t\t\t\t\t\&quot;value\&quot;: \&quot;${Value}\&quot;,\n\t\t\t\t\t\t\t\&quot;Ccy\&quot;: \&quot;${Ccy}\&quot;\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\&quot;ChrgBr\&quot;: \&quot;${ChrgBr}\&quot;,\n\t\t\t\t\t\t\&quot;Dbtr\&quot;: {\n\t\t\t\t\t\t\t\&quot;Nm\&quot;: \&quot;${DbtrNm}\&quot;,\n\t\t\t\t\t\t\t\&quot;Id\&quot;: {\n\t\t\t\t\t\t\t\t\&quot;OrgId\&quot;: {\n\t\t\t\t\t\t\t\t\t\&quot;Othr\&quot;: [\n\t\t\t\t\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\t\t\t\t\&quot;Id\&quot;: \&quot;${OrgIdId}\&quot;\n\t\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t\t]\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\&quot;DbtrAcct\&quot;: {\n\t\t\t\t\t\t\t\&quot;Id\&quot;: {\n\t\t\t\t\t\t\t\t\&quot;Othr\&quot;: {\n\t\t\t\t\t\t\t\t\t\&quot;Id\&quot;: \&quot;${DbtrAcctId}\&quot;\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t},\n\t\t\t\t\t\t\t\&quot;Tp\&quot;: {\n\t\t\t\t\t\t\t\t\&quot;Prtry\&quot;: \&quot;${TpPrtry}\&quot;\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\&quot;DbtrAgt\&quot;: {\n\t\t\t\t\t\t\t\&quot;FinInstnId\&quot;: {\n\t\t\t\t\t\t\t\t\&quot;Othr\&quot;: {\n\t\t\t\t\t\t\t\t\t\&quot;Id\&quot;: \&quot;${DbtrAgtId}\&quot;\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\&quot;CdtrAgt\&quot;: {\n\t\t\t\t\t\t\t\&quot;FinInstnId\&quot;: {\n\t\t\t\t\t\t\t\t\&quot;Othr\&quot;: {\n\t\t\t\t\t\t\t\t\t\&quot;Id\&quot;: \&quot;${CdtrAgtId}\&quot;\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\&quot;Cdtr\&quot;: {\n\t\t\t\t\t\t\t\&quot;Nm\&quot;: \&quot;${CdtrNm}\&quot;,\n\t\t\t\t\t\t\t\&quot;Id\&quot;: {\n\t\t\t\t\t\t\t\t\&quot;PrvtId\&quot;: {\n\t\t\t\t\t\t\t\t\t\&quot;Othr\&quot;: [\n\t\t\t\t\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\t\t\t\t\&quot;Id\&quot;: \&quot;${PrvtIdId}\&quot;\n\t\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t\t]\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\&quot;CdtrAcct\&quot;: {\n\t\t\t\t\t\t\t\&quot;Id\&quot;: {\n\t\t\t\t\t\t\t\t\&quot;Othr\&quot;: {\n\t\t\t\t\t\t\t\t\t\&quot;Id\&quot;: \&quot;${CdtrAcctOthrId}\&quot;\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t},\n\t\t\t\t\t\t\t\&quot;Tp\&quot;: {\n\t\t\t\t\t\t\t\t\&quot;Prtry\&quot;: \&quot;${CdtrAcctTpPrtry}\&quot;\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\&quot;RmtInf\&quot;: {\n\t\t\t\t\t\t\t\&quot;RmtInf\&quot;: [\n\t\t\t\t\t\t\t\t\&quot;${RmtInfRmtInf}\&quot;\n\t\t\t\t\t\t\t]\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\&quot;SplmtryData\&quot;: [\n\t\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\t\&quot;Envlp\&quot;: {\n\t\t\t\t\t\t\t\t\t\&quot;Dtl\&quot;: {\n\t\t\t\t\t\t\t\t\t\t\&quot;Dbtr\&quot;: {\n\t\t\t\t\t\t\t\t\t\t\t\&quot;RsdntSts\&quot;: \&quot;${EnvlpRsdntSts}\&quot;,\n\t\t\t\t\t\t\t\t\t\t\t\&quot;TwnNm\&quot;: \&quot;${EnvlpTwnNm}\&quot;\n\t\t\t\t\t\t\t\t\t\t},\n\t\t\t\t\t\t\t\t\t\t\&quot;Cdtr\&quot;: {\n\t\t\t\t\t\t\t\t\t\t\t\&quot;Tp\&quot;: \&quot;${CdtrTp}\&quot;,\n\t\t\t\t\t\t\t\t\t\t\t\&quot;RsdntSts\&quot;: \&quot;${CdtrRsdntSts}\&quot;,\n\t\t\t\t\t\t\t\t\t\t\t\&quot;TwnNm\&quot;: \&quot;${CdtrTwnNm}\&quot;\n\t\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t]\n\t\t\t\t\t}\n\t\t\t\t]\n\t\t\t}\n\t\t}\n\t}\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Basic QWRtaW5pc3RyYXRvcjptYW5hZ2U=</value>
      <webElementGuid>ff09aa31-595c-4e0d-a1a4-22c5142a3d02</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>d89492fd-3e2a-40e3-91d1-006429e47720</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>10.2.3</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${url}/credit-transfer</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.url</defaultValue>
      <description></description>
      <id>1930b402-92d6-494b-afe3-92efbfdcb05f</id>
      <masked>false</masked>
      <name>url</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d65d960c-dd58-48d6-9d43-31cd13095f9a</id>
      <masked>false</masked>
      <name>AppHdrId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>9058b785-5cce-447c-bef0-148cd6d122be</id>
      <masked>false</masked>
      <name>ToId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>45eee4f1-bf17-49ee-b7df-e5239311cd30</id>
      <masked>false</masked>
      <name>BizMsgIdr</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1ce64c9b-a7c4-4d03-b16f-c26e8d42be3f</id>
      <masked>false</masked>
      <name>MsgDefIdr</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d70f26fb-1fa9-4625-84ff-a0f6d2918846</id>
      <masked>false</masked>
      <name>BizSvc</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4e3339e5-e25c-4ff7-a6a2-c5cd2e9e11d3</id>
      <masked>false</masked>
      <name>CreDt</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d5208cfa-2db1-4d24-8ef1-d5e792ef2951</id>
      <masked>false</masked>
      <name>GrpHdrCreDtTm</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>667349a5-a614-45e6-b3a4-f8ec7dc742c7</id>
      <masked>false</masked>
      <name>GrpHdrMsgId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ad86ed6b-9c48-495a-b143-81d6a75dd3d1</id>
      <masked>false</masked>
      <name>GrpHdrNbOfTxs</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>7e480fb0-6032-419f-937e-4814a7cd92f3</id>
      <masked>false</masked>
      <name>SttlmInfSttlmMtd</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2c41cd39-5352-4d65-906c-b5d9f1a62856</id>
      <masked>false</masked>
      <name>PmtIdEndToEndId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f7579339-294e-4394-9505-7387e54aa3db</id>
      <masked>false</masked>
      <name>PmtIdTxId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1633f7bd-7a85-42de-b87b-15d64bbb114d</id>
      <masked>false</masked>
      <name>LclInstrmPrtry</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>968c0b81-14c6-4524-bbdb-ab33855a2ca8</id>
      <masked>false</masked>
      <name>CtgyPurpPrtry</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>988d68e5-9133-45f5-a827-41ccba21612c</id>
      <masked>false</masked>
      <name>ChrgBr</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>bb93428c-cf8d-48ca-ae36-e75e6200ba6c</id>
      <masked>false</masked>
      <name>Value</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>330acf03-e1ba-4491-9a2f-6a4496df9b1b</id>
      <masked>false</masked>
      <name>Ccy</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>8f81fe82-f18d-4ddd-a6d0-253d331a66d2</id>
      <masked>false</masked>
      <name>DbtrNm</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>689629e8-5da8-411f-9dec-34ee8211f25a</id>
      <masked>false</masked>
      <name>OrgIdId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b2fe0653-30e4-430c-b83b-bdfbce53ba39</id>
      <masked>false</masked>
      <name>DbtrAcctId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e6c3777b-6d7e-4f2b-9890-de03ec7f1359</id>
      <masked>false</masked>
      <name>TpPrtry</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b9dafcce-dda7-4c47-bb20-6c24f403e69b</id>
      <masked>false</masked>
      <name>DbtrAgtId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b299a78f-9872-4c8e-91ce-a35fdfbbe6be</id>
      <masked>false</masked>
      <name>CdtrAgtId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e59d3b3e-e549-477c-bc94-32dff1e26475</id>
      <masked>false</masked>
      <name>CdtrNm</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>a09b19ac-0144-4d0f-9926-0cf6aae0e844</id>
      <masked>false</masked>
      <name>PrvtIdId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>919b1d6b-4085-4f54-a0d2-ac122c1b4c0e</id>
      <masked>false</masked>
      <name>CdtrAcctOthrId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>a7d19cb5-c57f-4711-8b74-62d7bd190620</id>
      <masked>false</masked>
      <name>CdtrAcctTpPrtry</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>3b471f6e-67c9-43e4-9670-87b68dda3aad</id>
      <masked>false</masked>
      <name>RmtInfRmtInf</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>30091a88-7834-44f7-a066-dbe6acc74169</id>
      <masked>false</masked>
      <name>EnvlpRsdntSts</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f9fd23df-7c01-4f27-92d4-ef54ab196a7b</id>
      <masked>false</masked>
      <name>EnvlpTwnNm</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d57b2e3e-7bd6-49c4-8241-ee3649597eee</id>
      <masked>false</masked>
      <name>CdtrTp</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>42f8d757-9bb5-4555-9348-ff7c26bd2539</id>
      <masked>false</masked>
      <name>CdtrRsdntSts</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>13617a8d-6ca9-42e3-ae08-cb9761040859</id>
      <masked>false</masked>
      <name>CdtrTwnNm</name>
   </variables>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
