<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>12.3. Reverse Credit Transfer - Failed - Duplicate Transaction</name>
   <tag></tag>
   <elementGuidId>15143781-3c65-4d73-a425-1729a9b47d50</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>false</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n\t\&quot;BusMsg\&quot;: {\n\t\t\&quot;AppHdr\&quot;: {\n\t\t\t\&quot;Fr\&quot;: {\n\t\t\t\t\&quot;FIId\&quot;: {\n\t\t\t\t\t\&quot;FinInstnId\&quot;: {\n\t\t\t\t\t\t\&quot;Othr\&quot;: {\n\t\t\t\t\t\t\t\&quot;Id\&quot;: \&quot;${AppHdrId}\&quot;\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t},\n\t\t\t\&quot;To\&quot;: {\n\t\t\t\t\&quot;FIId\&quot;: {\n\t\t\t\t\t\&quot;FinInstnId\&quot;: {\n\t\t\t\t\t\t\&quot;Othr\&quot;: {\n\t\t\t\t\t\t\t\&quot;Id\&quot;: \&quot;${ToId}\&quot;\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t},\n\t\t\t\&quot;BizMsgIdr\&quot;: \&quot;${BizMsgIdr}\&quot;,\n\t\t\t\&quot;MsgDefIdr\&quot;: \&quot;${MsgDefIdr}\&quot;,\n\t\t\t\&quot;CreDt\&quot;: \&quot;${CreDt}\&quot;\n\t\t},\n\t\t\&quot;Document\&quot;: {\n\t\t\t\&quot;FIToFICstmrCdtTrf\&quot;: {\n\t\t\t\t\&quot;GrpHdr\&quot;: {\n\t\t\t\t\t\&quot;MsgId\&quot;: \&quot;${GrpHdrMsgId}\&quot;,\n\t\t\t\t\t\&quot;CreDtTm\&quot;: \&quot;${GrpHdrCreDtTm}\&quot;,\n\t\t\t\t\t\&quot;NbOfTxs\&quot;: \&quot;${GrpHdrNbOfTxs}\&quot;,\n\t\t\t\t\t\&quot;SttlmInf\&quot;: {\n\t\t\t\t\t\t\&quot;SttlmMtd\&quot;: \&quot;${SttlmInfSttlmMtd}\&quot;\n\t\t\t\t\t}\n\t\t\t\t},\n\t\t\t\t\&quot;CdtTrfTxInf\&quot;: [\n\t\t\t\t\t{\n\t\t\t\t\t\t\&quot;PmtId\&quot;: {\n\t\t\t\t\t\t\t\&quot;EndToEndId\&quot;: \&quot;${PmtIdEndToEndId}\&quot;,\n\t\t\t\t\t\t\t\&quot;TxId\&quot;: \&quot;${PmtIdTxId}\&quot;,\n\t\t\t\t\t\t\t\&quot;ClrSysRef\&quot;: \&quot;${ClrSysRef}\&quot;\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\&quot;PmtTpInf\&quot;: {\n\t\t\t\t\t\t\t\&quot;LclInstrm\&quot;: {\n\t\t\t\t\t\t\t\t\&quot;Prtry\&quot;: \&quot;${LclInstrmPrtry}\&quot;\n\t\t\t\t\t\t\t},\n\t\t\t\t\t\t\t\&quot;CtgyPurp\&quot;: {\n\t\t\t\t\t\t\t\t\&quot;Prtry\&quot;: \&quot;${CtgyPurpPrtry}\&quot;\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\&quot;IntrBkSttlmAmt\&quot;: {\n\t\t\t\t\t\t\t\&quot;value\&quot;: \&quot;${Value}\&quot;,\n\t\t\t\t\t\t\t\&quot;Ccy\&quot;: \&quot;${Ccy}\&quot;\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\&quot;IntrBkSttlmDt\&quot;: \&quot;${IntrBkSttlmDt}\&quot;,\n\t\t\t\t\t\t\&quot;ChrgBr\&quot;: \&quot;${ChrgBr}\&quot;,\n\t\t\t\t\t\t\&quot;Dbtr\&quot;: {\n\t\t\t\t\t\t\t\&quot;Nm\&quot;: \&quot;${DbtrNm}\&quot;,\n\t\t\t\t\t\t\t\&quot;Id\&quot;: {\n\t\t\t\t\t\t\t\t\&quot;PrvtId\&quot;: {\n\t\t\t\t\t\t\t\t\t\&quot;Othr\&quot;: [\n\t\t\t\t\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\t\t\t\t\&quot;Id\&quot;: \&quot;${OrgIdId}\&quot;\n\t\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t\t]\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\&quot;DbtrAcct\&quot;: {\n\t\t\t\t\t\t\t\&quot;Id\&quot;: {\n\t\t\t\t\t\t\t\t\&quot;Othr\&quot;: {\n\t\t\t\t\t\t\t\t\t\&quot;Id\&quot;: \&quot;${DbtrAcctId}\&quot;\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t},\n\t\t\t\t\t\t\t\&quot;Tp\&quot;: {\n\t\t\t\t\t\t\t\t\&quot;Prtry\&quot;: \&quot;${TpPrtry}\&quot;\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\&quot;DbtrAgt\&quot;: {\n\t\t\t\t\t\t\t\&quot;FinInstnId\&quot;: {\n\t\t\t\t\t\t\t\t\&quot;Othr\&quot;: {\n\t\t\t\t\t\t\t\t\t\&quot;Id\&quot;: \&quot;${DbtrAgtId}\&quot;\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\&quot;CdtrAgt\&quot;: {\n\t\t\t\t\t\t\t\&quot;FinInstnId\&quot;: {\n\t\t\t\t\t\t\t\t\&quot;Othr\&quot;: {\n\t\t\t\t\t\t\t\t\t\&quot;Id\&quot;: \&quot;${CdtrAgtId}\&quot;\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\&quot;Cdtr\&quot;: {\n\t\t\t\t\t\t\t\&quot;Nm\&quot;: \&quot;${CdtrNm}\&quot;,\n\t\t\t\t\t\t\t\&quot;Id\&quot;: {\n\t\t\t\t\t\t\t\t\&quot;PrvtId\&quot;: {\n\t\t\t\t\t\t\t\t\t\&quot;Othr\&quot;: [\n\t\t\t\t\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\t\t\t\t\&quot;Id\&quot;: \&quot;${PrvtIdId}\&quot;\n\t\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t\t]\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\&quot;CdtrAcct\&quot;: {\n\t\t\t\t\t\t\t\&quot;Id\&quot;: {\n\t\t\t\t\t\t\t\t\&quot;Othr\&quot;: {\n\t\t\t\t\t\t\t\t\t\&quot;Id\&quot;: \&quot;${CdtrAcctOthrId}\&quot;\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t},\n\t\t\t\t\t\t\t\&quot;Tp\&quot;: {\n\t\t\t\t\t\t\t\t\&quot;Prtry\&quot;: \&quot;${CdtrAcctTpPrtry}\&quot;\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\&quot;RmtInf\&quot;: {\n\t\t\t\t\t\t\t\&quot;Ustrd\&quot;: [\n\t\t\t\t\t\t\t\t\&quot;${RmtInfUstrd}\&quot;\n\t\t\t\t\t\t\t]\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\&quot;SplmtryData\&quot;: [\n\t\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\t\&quot;Envlp\&quot;: {\n\t\t\t\t\t\t\t\t\t\&quot;Dtl\&quot;: {\n\t\t\t\t\t\t\t\t\t\t\&quot;Dbtr\&quot;: {\n\t\t\t\t\t\t\t\t\t\t\t\&quot;RsdntSts\&quot;: \&quot;${EnvlpRsdntSts}\&quot;,\n\t\t\t\t\t\t\t\t\t\t\t\&quot;TwnNm\&quot;: \&quot;${EnvlpTwnNm}\&quot;\n\t\t\t\t\t\t\t\t\t\t},\n\t\t\t\t\t\t\t\t\t\t\&quot;Cdtr\&quot;: {\n\t\t\t\t\t\t\t\t\t\t\t\&quot;Tp\&quot;: \&quot;${CdtrTp}\&quot;,\n\t\t\t\t\t\t\t\t\t\t\t\&quot;RsdntSts\&quot;: \&quot;${CdtrRsdntSts}\&quot;,\n\t\t\t\t\t\t\t\t\t\t\t\&quot;TwnNm\&quot;: \&quot;${CdtrTwnNm}\&quot;\n\t\t\t\t\t\t\t\t\t\t},\n\t\t\t\t\t\t\t\t\t\t\&quot;RltdEndToEndId\&quot;: \&quot;${RltdEndToEndId}\&quot;\n\t\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t]\n\t\t\t\t\t}\n\t\t\t\t]\n\t\t\t}\n\t\t}\n\t}\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Basic QWRtaW5pc3RyYXRvcjptYW5hZ2U=</value>
      <webElementGuid>88652042-78ab-401a-9665-f147d92e2fca</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>8dcbee65-52f4-4812-ac1a-2f6ee0b8a21e</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>10.2.3</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${url}/reverse-credit-transfer</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.url</defaultValue>
      <description></description>
      <id>18397afe-2f1d-490c-8bdf-0e524bf1f18f</id>
      <masked>false</masked>
      <name>url</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>a559e5c4-1f2c-4c4c-90e4-47b38938883e</id>
      <masked>false</masked>
      <name>AppHdrId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>069590ca-3e39-4ca1-8c4b-4117377824fa</id>
      <masked>false</masked>
      <name>ToId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>33804c57-85d8-47f1-a904-b7737e01728b</id>
      <masked>false</masked>
      <name>BizMsgIdr</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>7374904c-d264-4124-b8ed-178dac1d485f</id>
      <masked>false</masked>
      <name>MsgDefIdr</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>a0a3f975-b5b3-4bf9-8b8e-046a7663cab1</id>
      <masked>false</masked>
      <name>CreDt</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>36f80b9e-2b07-4e4a-9966-5d0448b24a5c</id>
      <masked>false</masked>
      <name>GrpHdrCreDtTm</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>eabbac2d-46ec-4d1c-8ae7-fb45540d5bc8</id>
      <masked>false</masked>
      <name>GrpHdrMsgId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b6168777-8e66-4311-87d7-45e694c67f5f</id>
      <masked>false</masked>
      <name>GrpHdrNbOfTxs</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>3d2e08b2-5bbf-4837-a894-f539e967d3f3</id>
      <masked>false</masked>
      <name>SttlmInfSttlmMtd</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ebc04b3e-7a50-4e16-8a04-2e0473aff032</id>
      <masked>false</masked>
      <name>PmtIdEndToEndId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>926ce45d-d9c7-4745-9e58-b98f90fba3b6</id>
      <masked>false</masked>
      <name>PmtIdTxId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>cac29fa7-d7cc-40af-a005-230a12eec0b0</id>
      <masked>false</masked>
      <name>ClrSysRef</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b481bc3b-ed36-48b6-973d-aec2dee28776</id>
      <masked>false</masked>
      <name>LclInstrmPrtry</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>53c28024-da9c-41d6-9f78-7b6f9a8c8d80</id>
      <masked>false</masked>
      <name>CtgyPurpPrtry</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>acf7a74e-3755-4ac8-a447-0ecdcc9d972b</id>
      <masked>false</masked>
      <name>IntrBkSttlmDt</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>08790a24-6095-4b6b-9172-f0add270b48c</id>
      <masked>false</masked>
      <name>ChrgBr</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>dde2b5f6-5ad8-4102-a216-b255adc258a1</id>
      <masked>false</masked>
      <name>Value</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ddb38e51-35ff-4f4e-8db3-198d0c79053c</id>
      <masked>false</masked>
      <name>Ccy</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>a7bca254-d486-4a04-91f6-0c63b8a69695</id>
      <masked>false</masked>
      <name>DbtrNm</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>3c9e025b-15e8-42a5-86f1-febd67a5b390</id>
      <masked>false</masked>
      <name>OrgIdId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0675061e-7d3d-4537-adf9-922957cb93aa</id>
      <masked>false</masked>
      <name>DbtrAcctId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>15a1f9e7-fe45-4cb9-b217-09096572bf76</id>
      <masked>false</masked>
      <name>TpPrtry</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>94e041c4-55ca-4798-89fc-089cd951b9b2</id>
      <masked>false</masked>
      <name>DbtrAgtId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>640a9232-2f31-488d-9fdb-a123c6026c57</id>
      <masked>false</masked>
      <name>CdtrAgtId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ca8baeff-ed5b-49f8-aaf1-d2bbf7f8ade5</id>
      <masked>false</masked>
      <name>CdtrNm</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>75f525cd-1421-4619-97ac-3c61ce5b8de3</id>
      <masked>false</masked>
      <name>PrvtIdId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b09282d2-53ed-4408-8523-6a1b3054a549</id>
      <masked>false</masked>
      <name>CdtrAcctOthrId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>7a9e5bee-31b5-43f6-a445-ff9cde2ab708</id>
      <masked>false</masked>
      <name>CdtrAcctTpPrtry</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>72042afd-19e6-444e-9399-167de0fb399c</id>
      <masked>false</masked>
      <name>RmtInfUstrd</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f4ca60de-ad58-4c4c-99ce-f48fde800744</id>
      <masked>false</masked>
      <name>EnvlpRsdntSts</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f2f4279c-15a2-4d9a-8a6a-890c595d7f93</id>
      <masked>false</masked>
      <name>EnvlpTwnNm</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>7f6309cc-3c6a-4156-ad1a-d329c54d4fc2</id>
      <masked>false</masked>
      <name>CdtrTp</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1c4c69b7-f146-4e71-9131-0e92004d3908</id>
      <masked>false</masked>
      <name>CdtrRsdntSts</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>cb13b48b-ccbd-4b08-b374-3bffb6b36e67</id>
      <masked>false</masked>
      <name>CdtrTwnNm</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b3459dcb-8809-4038-bad1-214b8e3b3505</id>
      <masked>false</masked>
      <name>RltdEndToEndId</name>
   </variables>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
