<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>9.3. Account Enquiry - Failed - Duplikat (U149)</name>
   <tag></tag>
   <elementGuidId>b0323f64-1d35-4432-aef6-b19c3214524a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>false</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n    \&quot;BusMsg\&quot;: {\n        \&quot;AppHdr\&quot;: {\n            \&quot;Fr\&quot;: {\n                \&quot;FIId\&quot;: {\n                    \&quot;FinInstnId\&quot;: {\n                        \&quot;Othr\&quot;: {\n                            \&quot;Id\&quot;: \&quot;${AppHdrId}\&quot;\n                        }\n                    }\n                }\n            },\n            \&quot;To\&quot;: {\n                \&quot;FIId\&quot;: {\n                    \&quot;FinInstnId\&quot;: {\n                        \&quot;Othr\&quot;: {\n                            \&quot;Id\&quot;: \&quot;${ToId}\&quot;\n                        }\n                    }\n                }\n            },\n            \&quot;BizMsgIdr\&quot;: \&quot;${BizMsgIdr}\&quot;,\n            \&quot;MsgDefIdr\&quot;: \&quot;${MsgDefIdr}\&quot;,\n            \&quot;CreDt\&quot;: \&quot;${CreDt}\&quot;\n        },\n        \&quot;Document\&quot;: {\n            \&quot;FIToFICstmrCdtTrf\&quot;: {\n                \&quot;GrpHdr\&quot;: {\n                    \&quot;CreDtTm\&quot;: \&quot;${GrpHdrCreDtTm}\&quot;,\n                    \&quot;MsgId\&quot;: \&quot;${GrpHdrMsgId}\&quot;,\n                    \&quot;NbOfTxs\&quot;: \&quot;${GrpHdrNbOfTxs}\&quot;,\n                    \&quot;SttlmInf\&quot;: {\n                        \&quot;SttlmMtd\&quot;: \&quot;${SttlmInfSttlmMtd}\&quot;\n                    }\n                },\n                \&quot;CdtTrfTxInf\&quot;: [\n                    {\n                        \&quot;PmtId\&quot;: {\n                            \&quot;EndToEndId\&quot;: \&quot;${PmtIdEndToEndId}\&quot;,\n                            \&quot;TxId\&quot;: \&quot;${PmtIdTxId}\&quot;,\n                            \&quot;ClrSysRef\&quot;: \&quot;${PmtIdClrSysRef}\&quot;\n                        },\n                        \&quot;PmtTpInf\&quot;: {\n                            \&quot;CtgyPurp\&quot;: {\n                                \&quot;Prtry\&quot;: \&quot;${CtgyPurpPrtry}\&quot;\n                            }\n                        },\n                        \&quot;IntrBkSttlmDt\&quot;: \&quot;${IntrBkSttlmDt}\&quot;,\n                        \&quot;ChrgBr\&quot;: \&quot;${ChrgBr}\&quot;,\n                        \&quot;Dbtr\&quot;: {},\n                        \&quot;DbtrAgt\&quot;: {\n                            \&quot;FinInstnId\&quot;: {\n                                \&quot;Othr\&quot;: {\n                                    \&quot;Id\&quot;: \&quot;${FinInstnIdOthrId}\&quot;\n                                }\n                            }\n                        },\n                        \&quot;CdtrAgt\&quot;: {\n                            \&quot;FinInstnId\&quot;: {\n                                \&quot;Othr\&quot;: {\n                                    \&quot;Id\&quot;: \&quot;${OthrId}\&quot;\n                                }\n                            }\n                        },\n                        \&quot;Cdtr\&quot;: {},\n                        \&quot;CdtrAcct\&quot;: {\n                            \&quot;Id\&quot;: {\n                                \&quot;Othr\&quot;: {\n                                    \&quot;Id\&quot;: \&quot;${CdtrAcctOthrId}\&quot;\n                                }\n                            }\n                        },\n                        \&quot;IntrBkSttlmAmt\&quot;: {\n                            \&quot;Value\&quot;: \&quot;${Value}\&quot;,\n                            \&quot;Ccy\&quot;: \&quot;${Ccy}\&quot;\n                        }\n                    }\n                ]\n            }\n        }\n    }\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Basic QWRtaW5pc3RyYXRvcjptYW5hZ2U=</value>
      <webElementGuid>bb34cc8f-f2bb-4d35-bcce-a75d8c53dd61</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>8fb6e5fe-acd0-4051-90fa-b88a964d8227</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>10.2.3</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${url}/account-enquiry</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.url</defaultValue>
      <description></description>
      <id>241f43a6-7534-4ba2-adcb-757366fac72f</id>
      <masked>false</masked>
      <name>url</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1042c514-04ad-45f3-883c-dabb275822ee</id>
      <masked>false</masked>
      <name>AppHdrId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c770d1c7-a0b9-4898-b1f7-e7718e8cfa9c</id>
      <masked>false</masked>
      <name>ToId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>fa099e01-7bba-4090-8670-027ddc7ec560</id>
      <masked>false</masked>
      <name>BizMsgIdr</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>559ed134-4141-4adb-b97d-318f615addf7</id>
      <masked>false</masked>
      <name>MsgDefIdr</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2d6fae47-4960-42b3-8101-f1ef7fa8022a</id>
      <masked>false</masked>
      <name>CreDt</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>44a94c87-ab57-475d-a779-7e2d81a3b25d</id>
      <masked>false</masked>
      <name>GrpHdrCreDtTm</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>e2410efd-cdcd-48c2-acff-99da46f94868</id>
      <masked>false</masked>
      <name>GrpHdrMsgId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>2e1e2cd8-bdd9-400f-8920-a8b343d87b58</id>
      <masked>false</masked>
      <name>GrpHdrNbOfTxs</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>4575ede2-bf25-4354-aec0-814373ebf9a8</id>
      <masked>false</masked>
      <name>SttlmInfSttlmMtd</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c2c0de96-0d33-455c-b9ea-ae1e3050455d</id>
      <masked>false</masked>
      <name>PmtIdEndToEndId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>892e7c0a-9e8f-450a-bc42-3ad2659dcf2d</id>
      <masked>false</masked>
      <name>PmtIdTxId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d923e670-22cd-4289-b6ef-ebf39322705f</id>
      <masked>false</masked>
      <name>PmtIdClrSysRef</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>fd3c0184-ba39-4efa-bb0d-39c0c75d8454</id>
      <masked>false</masked>
      <name>CtgyPurpPrtry</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>43156c1f-05fd-4677-81ec-b66f03205aea</id>
      <masked>false</masked>
      <name>IntrBkSttlmDt</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>73c25f8d-2ac4-4322-bc51-388e0ee8b62e</id>
      <masked>false</masked>
      <name>ChrgBr</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>cc41b4d6-ad33-47ae-8c34-0288905629af</id>
      <masked>false</masked>
      <name>FinInstnIdOthrId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>989bb0f6-5fb2-4f23-aeb2-58650f581575</id>
      <masked>false</masked>
      <name>OthrId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d52aee15-9c0d-4e37-96ae-04547f349fd9</id>
      <masked>false</masked>
      <name>CdtrAcctOthrId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1d36816b-fd06-486c-9ada-0cc7c451d6a2</id>
      <masked>false</masked>
      <name>Value</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>83c1d0d2-8028-422d-96bc-aa2d05a191dc</id>
      <masked>false</masked>
      <name>Ccy</name>
   </variables>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
