<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Settlement Confirmation</name>
   <tag></tag>
   <elementGuidId>8d4c7cf8-8a0f-4584-95c9-f738169afcbe</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>false</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n    \&quot;BusMsg\&quot;: {\n        \&quot;AppHdr\&quot;: {\n            \&quot;Fr\&quot;: {\n                \&quot;FIId\&quot;: {\n                    \&quot;FinInstnId\&quot;: {\n                        \&quot;Othr\&quot;: {\n                            \&quot;Id\&quot;: \&quot;${AppHdrId}\&quot;\n                        }\n                    }\n                }\n            },\n            \&quot;To\&quot;: {\n                \&quot;FIId\&quot;: {\n                    \&quot;FinInstnId\&quot;: {\n                        \&quot;Othr\&quot;: {\n                            \&quot;Id\&quot;: \&quot;${ToId}\&quot;\n                        }\n                    }\n                }\n            },\n            \&quot;BizMsgIdr\&quot;: \&quot;${BizMsgIdr}\&quot;,\n            \&quot;MsgDefIdr\&quot;: \&quot;${MsgDefIdr}\&quot;,\n            \&quot;BizSvc\&quot;: \&quot;${BizSvc}\&quot;,\n            \&quot;CreDt\&quot;: \&quot;${CreDt}\&quot;\n        },\n        \&quot;Document\&quot;: {\n            \&quot;FIToFIPmtStsRpt\&quot;: {\n                \&quot;GrpHdr\&quot;: {\n                    \&quot;MsgId\&quot;: \&quot;${GrpHdrMsgId}\&quot;,\n                    \&quot;CreDtTm\&quot;: \&quot;${GrpHdrCreDtTm}\&quot;\n                },\n                \&quot;OrgnlGrpInfAndSts\&quot;: [\n                    {\n                        \&quot;OrgnlMsgId\&quot;: \&quot;${OrgnlMsgId}\&quot;,\n                        \&quot;OrgnlMsgNmId\&quot;: \&quot;pacs.008.001.08\&quot;\n                    }\n                ],\n                \&quot;TxInfAndSts\&quot;: [\n                    {\n                        \&quot;OrgnlEndToEndId\&quot;: \&quot;${TxInfAndStsOrgnlEndToEndId}\&quot;,\n                        \&quot;OrgnlTxId\&quot;: \&quot;${TxInfAndStsOrgnlTxId}\&quot;,\n                        \&quot;TxSts\&quot;: \&quot;${TxInfAndStsTxSts}\&quot;,\n                        \&quot;StsRsnInf\&quot;: [\n                            {\n                                \&quot;Rsn\&quot;: {\n                                    \&quot;Prtry\&quot;: \&quot;${StsRsnInfPrtry}\&quot;\n                                }\n                            }\n                        ],\n                        \&quot;ClrSysRef\&quot;: \&quot;${ClrSysRef}\&quot;,\n                        \&quot;OrgnlTxRef\&quot;: {\n                            \&quot;IntrBkSttlmDt\&quot;: \&quot;${IntrBkSttlmDt}\&quot;,\n                            \&quot;Dbtr\&quot;: {\n                                \&quot;Pty\&quot;: {\n                                    \&quot;Nm\&quot;: \&quot;${DbtrNm}\&quot;\n                                }\n                            },\n                            \&quot;DbtrAcct\&quot;: {\n                                \&quot;Id\&quot;: {\n                                    \&quot;Othr\&quot;: {\n                                        \&quot;Id\&quot;: \&quot;${DbtrAcctId}\&quot;\n                                    }\n                                }\n                            },\n                            \&quot;DbtrAgt\&quot;: {\n                                \&quot;FinInstnId\&quot;: {\n                                    \&quot;Othr\&quot;: {\n                                        \&quot;Id\&quot;: \&quot;${DbtrAgtId}\&quot;\n                                    }\n                                }\n                            },\n                            \&quot;CdtrAgt\&quot;: {\n                                \&quot;FinInstnId\&quot;: {\n                                    \&quot;Othr\&quot;: {\n                                        \&quot;Id\&quot;: \&quot;${CdtrAgtId}\&quot;\n                                    }\n                                }\n                            },\n                            \&quot;Cdtr\&quot;: {\n                                \&quot;Pty\&quot;: {\n                                    \&quot;Nm\&quot;: \&quot;${CdtrNm}\&quot;\n                                }\n                            },\n                            \&quot;CdtrAcct\&quot;: {\n                                \&quot;Id\&quot;: {\n                                    \&quot;Othr\&quot;: {\n                                        \&quot;Id\&quot;: \&quot;${CdtrAcctOthrId}\&quot;\n                                    }\n                                },\n                                \&quot;Tp\&quot;: {\n                                    \&quot;Prtry\&quot;: \&quot;${TpPrtry}\&quot;\n                                }\n                            }\n                        },\n                        \&quot;SplmtryData\&quot;: [\n                            {\n                                \&quot;Envlp\&quot;: {\n                                    \&quot;Dtl\&quot;: {\n                                        \&quot;DbtrAgtAcct\&quot;: {\n                                            \&quot;Id\&quot;: {\n                                                \&quot;Othr\&quot;: {\n                                                    \&quot;Id\&quot;: \&quot;${DbtrAgtAcctId}\&quot;\n                                                }\n                                            }\n                                        },\n                                        \&quot;CdtrAgtAcct\&quot;: {\n                                            \&quot;Id\&quot;: {\n                                                \&quot;Othr\&quot;: {\n                                                    \&quot;Id\&quot;: \&quot;${CdtrAgtAcctId}\&quot;\n                                                }\n                                            }\n                                        }\n                                    }\n                                }\n                            }\n                        ]\n                    }\n                ]\n            }\n        }\n    }\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Authorization</name>
      <type>Main</type>
      <value>Basic QWRtaW5pc3RyYXRvcjptYW5hZ2U=</value>
      <webElementGuid>ed9b4be6-34b3-430e-9c8d-c85b1d5979f3</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>6609bcbe-de0d-4530-872a-f73d2c502758</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>10.2.3</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${url}/settlement-credit-transfer</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.url</defaultValue>
      <description></description>
      <id>e6864599-7113-4a9e-85a7-759a9f568c06</id>
      <masked>false</masked>
      <name>url</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>daf4b555-d26e-4548-a94c-d0af2071aa6c</id>
      <masked>false</masked>
      <name>AppHdrId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>6f83cfd4-1e7c-411d-8a35-427af4294eed</id>
      <masked>false</masked>
      <name>ToId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>162696d3-6a33-47e8-8838-a52932ba977b</id>
      <masked>false</masked>
      <name>BizMsgIdr</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>64837fdd-9165-4d37-91f7-ce6a36e959bd</id>
      <masked>false</masked>
      <name>MsgDefIdr</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b633981a-a8e5-4843-bc25-c0cb7ce40988</id>
      <masked>false</masked>
      <name>BizSvc</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>7b069bf9-bfcd-4f88-9106-aff9a2a751b0</id>
      <masked>false</masked>
      <name>CreDt</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>39aad31e-ac12-4afa-9ed0-bec173f6ad7f</id>
      <masked>false</masked>
      <name>GrpHdrCreDtTm</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>ca60ece7-09a8-43ee-ad3a-93d757be6666</id>
      <masked>false</masked>
      <name>GrpHdrMsgId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>77edbc6d-2e51-41b9-8a2d-1cd43ea6a96d</id>
      <masked>false</masked>
      <name>OrgnlMsgId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>f3c7c8bf-b248-4dd8-add6-21910f2ac6d6</id>
      <masked>false</masked>
      <name>OrgnlMsgNmId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c25eb42a-4ff4-41de-a180-c05870e30435</id>
      <masked>false</masked>
      <name>TxInfAndStsOrgnlEndToEndId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>c02b4c4e-6f69-4e9e-953f-58bc60ca1ed5</id>
      <masked>false</masked>
      <name>TxInfAndStsOrgnlTxId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>bff5d9e0-00c0-4719-8204-504f5d407fdf</id>
      <masked>false</masked>
      <name>TxInfAndStsTxSts</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>9ad4d3cc-5ef2-4d0b-be2c-64d274b236f0</id>
      <masked>false</masked>
      <name>StsRsnInfPrtry</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>fecedab2-5ce9-47bb-a7eb-f20364a60699</id>
      <masked>false</masked>
      <name>ClrSysRef</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b83cb8a6-d25c-4b22-bea2-11165cd43748</id>
      <masked>false</masked>
      <name>IntrBkSttlmDt</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>0d2d5db0-e3c6-44ce-9345-9a135c4f9802</id>
      <masked>false</masked>
      <name>DbtrNm</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>38923f47-58e0-40d0-8bc5-6b648660953a</id>
      <masked>false</masked>
      <name>DbtrAcctId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>3d58b681-703c-4bf4-801b-b76a48be4bac</id>
      <masked>false</masked>
      <name>DbtrAgtId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>d3dee9aa-5047-4f84-a216-670ebae9df58</id>
      <masked>false</masked>
      <name>CdtrAgtId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>1141c2f3-b25a-4d58-a697-3351aaabf117</id>
      <masked>false</masked>
      <name>CdtrNm</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>a04d346b-eb22-43a9-ba1b-f723cfbde19c</id>
      <masked>false</masked>
      <name>CdtrAcctOthrId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>a6ce3689-e850-4434-898c-46908af2ec87</id>
      <masked>false</masked>
      <name>TpPrtry</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>b040252c-ef7c-446d-9d10-3ee52f0299f2</id>
      <masked>false</masked>
      <name>DbtrAgtAcctId</name>
   </variables>
   <variables>
      <defaultValue>''</defaultValue>
      <description></description>
      <id>cb532834-5180-4563-8a88-09ba1bdb4215</id>
      <masked>false</masked>
      <name>CdtrAgtAcctId</name>
   </variables>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
